# Uso de los comandos *concat* y *append*

## Importar librerias

In [2]:
# Actualizar pandas
!pip install --upgrade pandas

In [3]:
# Importar librerias
import pandas as pd
import numpy as np
pd.__version__

'1.3.5'

## Proceso para crear y preparar datos con dos números decimales

In [4]:
# Pandas. codigo para crear numeros con dos decimales
pd.options.display.float_format = '{:.2f}'.format

In [15]:
# Numpy. codigo para crear numeros con dos decimales
np.set_printoptions(precision=1)

### Generar números aleatorios con Numpy

In [6]:
# Genera número aleatorios del 0 al 1
np.random.rand()

0.40607866722061825

In [7]:
# Genera números aleatorios entre 1 y -1
np.random.randn()

-0.18830448372919287

### Generar números aletorios positivos en una matriz de 2 x 5

In [8]:
#Numpy. Generar número positivos en una matriz de 2x5 -> 2 listas, por 5 valores
np.random.rand(2,5)

array([[0.43, 0.37, 0.96, 0.25, 0.56],
       [0.81, 0.7 , 0.26, 0.04, 0.62]])

In [16]:
# Almacenar el anterior codigo en una variable x1
x1 = np.random.rand(2,5) * 100
x1

array([[15. , 79.3, 17.2, 98.7, 38.4],
       [87.4, 30.9,  2.9, 57.3, 69.7]])

In [17]:
# Crear otra mariz y almacenarla en la variabl x2
x2 = np.random.rand(2,5) * -1
x2

array([[-1. , -1. , -0.6, -0.2, -0.4],
       [-0.4, -0.8, -0.5, -0.4, -0.8]])

## Concatenar Matrices
Numpy puede concatenar matrices usando la función *concatenate*

### Concatenar Matrices con Numpy

In [18]:
# unir las matrices usando la función concatenate
np.concatenate([x1,x2])

array([[15. , 79.3, 17.2, 98.7, 38.4],
       [87.4, 30.9,  2.9, 57.3, 69.7],
       [-1. , -1. , -0.6, -0.2, -0.4],
       [-0.4, -0.8, -0.5, -0.4, -0.8]])

In [19]:
# ver la dimensiones del objeto creado
np.concatenate([x1,x2]).shape

(4, 5)

Se creo un objeto de 4 columnas con 5 valores cada una. En el anterior ejemplo se creo un matriz a lo largo del eje de las filas

#### Crear Matrices a lo largo de los ejes de las columnas

In [20]:
np.concatenate([x1,x2], axis = 1)

array([[15. , 79.3, 17.2, 98.7, 38.4, -1. , -1. , -0.6, -0.2, -0.4],
       [87.4, 30.9,  2.9, 57.3, 69.7, -0.4, -0.8, -0.5, -0.4, -0.8]])

In [22]:
# ver la dimensiones del objeto creado
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

Se creo un objeto de 2 columnas con 10 valores cada una

### Concatenar Matrices con Pandas

In [26]:
# Crear set de datos
# se toma la primera columna de x1
# de definen los índices
s1 = pd.Series(x1[0],index = ['a','b','c','d','e'])
s1

a   14.98
b   79.30
c   17.21
d   98.73
e   38.41
dtype: float64

In [27]:
# Crear una segunda serie de elementos
s2 = pd.Series(x2[0], index = ['c','d','e','f','g'])
s2

c   -1.00
d   -0.99
e   -0.58
f   -0.24
g   -0.39
dtype: float64

### Concatenar

In [29]:
# concatenar a lo largo de las filas
pd.concat([s1,s2])

a   14.98
b   79.30
c   17.21
d   98.73
e   38.41
c   -1.00
d   -0.99
e   -0.58
f   -0.24
g   -0.39
dtype: float64

In [30]:
# concatenar a lo largo de las columnas
pd.concat([s1,s2], axis=1)

0     1
a 14.98   NaN
b 79.30   NaN
c 17.21 -1.00
d 98.73 -0.99
e 38.41 -0.58
f   NaN -0.24
g   NaN -0.39

**Nota** -> El anterior ejemplo coloca los calores haciendo coincidir los indices descritos anteriormente en ambos elementos y creanod NaN donde no existen coincidencias

### Concatenar matrices SIN respetar los índices

## Concatenar Dataframes

In [31]:
# Crear dataframe 1
df1 = pd.DataFrame(np.random.rand(3,2) * 10, columns=['a','b'])
df1

a    b
0 3.51 2.35
1 1.15 7.75
2 8.91 4.56

In [33]:
# Crear dataframe 2
df2 = pd.DataFrame(np.random.rand(3,2) * -1, columns=['a','b'], index = [2,3,4])
df2

a     b
2 -0.14 -0.12
3 -0.31 -0.01
4 -0.57 -0.87

In [34]:
# concatenar dataframes a lo largo de las filas
pd.concat([df1,df2])

a     b
0  3.51  2.35
1  1.15  7.75
2  8.91  4.56
2 -0.14 -0.12
3 -0.31 -0.01
4 -0.57 -0.87

In [36]:
# concatenar dataframes a lo largo de las columnas
pd.concat([df1,df2], axis = 1)

a    b     a     b
0 3.51 2.35   NaN   NaN
1 1.15 7.75   NaN   NaN
2 8.91 4.56 -0.14 -0.12
3  NaN  NaN -0.31 -0.01
4  NaN  NaN -0.57 -0.87

In [38]:
# hacer énfasis del índice que se repite en ambos dataframes
pd.concat([df1,df2], axis = 1, join = 'inner')
# y se obtiene únicamente fila del indice que comparten ambos dataframes

a    b     a     b
2 8.91 4.56 -0.14 -0.12

### Concatenar dataframes SIN respetar los índices

## Juntar dataframes usando el comando *append*

In [39]:
df1.append(df2)

a     b
0  3.51  2.35
1  1.15  7.75
2  8.91  4.56
2 -0.14 -0.12
3 -0.31 -0.01
4 -0.57 -0.87

In [40]:
# Se puede pegar varias veces
df1.append(df2).append(df2)

a     b
0  3.51  2.35
1  1.15  7.75
2  8.91  4.56
2 -0.14 -0.12
3 -0.31 -0.01
4 -0.57 -0.87
2 -0.14 -0.12
3 -0.31 -0.01
4 -0.57 -0.87

In [41]:
# traspuesta. Invertir el orden. Poner columnas como indices y poner indices como columnas
df1.T

0    1    2
a 3.51 1.15 8.91
b 2.35 7.75 4.56

In [42]:
# hacer append en la traspuesta
df1.T.append(df2.T).T

a    b     a     b
0 3.51 2.35   NaN   NaN
1 1.15 7.75   NaN   NaN
2 8.91 4.56 -0.14 -0.12
3  NaN  NaN -0.31 -0.01
4  NaN  NaN -0.57 -0.87